Repository NADOOIT/NADOO-Wiki, pull requests merged in 2025-09, with the labels that each got.

#558 docs: Update Zeiterfassung & Nachweise (Issue #547)
  docs/01-organisation/01-zeiterfassung/README.md
  docs/01-organisation/02-zeit_und_ausbildungsnachweise/01-beispiele/README.md
Labels: documentation

#588 Update README.md
  docs/00-willkommen/01-leitfaden/README.md
Labels: korrektur-inhalt

#585 Update README.md
  docs/06-entwicklung/02-clean_architecture/README.md
Labels: bug, documentation, onboarding
