Repository NADOOIT/NADOO-Wiki, pull requests merged in 2025-04, with the labels that each got.

#197 Korrekturen auf der Einstiegsseite
  README.md
Labels: Rechtschreibung

#207 Anpassung Anrede
  docs/1/3/README.md
  docs/1/4/README.md
  docs/1/8/README.md
Labels: stilanpassung

#232 Korrekturen
  docs/1/4/README.md
  docs/2/2/README.md
Labels: rechtschreibung

#363 Korrekturdurchsicht: 01-organisation
  docs/01-organisation/01-zeit-ausbildungsnachweise/01-beispiele/README.md
  docs/01-organisation/01-zeit-ausbildungsnachweise/03-ueberpruefung/README.md
  docs/01-organisation/01-zeit-ausbildungsnachweise/README.md
  docs/01-organisation/04-krankmeldungen/README.md
  docs/01-organisation/07-feedback-kultur/README.md
  docs/01-organisation/09-jobrotation-weiterbildung/README.md
  docs/01-organisation/10-teamkoordination/README.md
  docs/01-organisation/11-vorbereitung-training/README.md
  docs/01-organisation/12-kaizen/README.md
  docs/02-tools/01-github/02-branches/01-protection/README.md
Labels: rechtschreibung, stilanpassung, organisation

#370 Korrekturdurchsicht
  docs/02-tools/02-vscode/02-plugins/README.md
  docs/02-tools/04-terminal/README.md
  docs/02-tools/05-ki/02-gemini/README.md
  docs/02-tools/05-ki/README.md
Labels: wiki, rechtschreibung, stilanpassung

#366 02-tools -> 01-github
  docs/04-tools/01-github/01-repository/README.md
Labels: rechtschreibung, stilanpassung, du-anrede

#377 Korrektur
  README.md
Labels: stilanpassung
